[[files]]
path = "/etc/tedge/tedge.toml"
type = "tedge.toml"

[[files]]
path = "/etc/tedge/mosquitto-conf/tedge-mosquitto.conf"
type = "tedge-mosquitto.conf"

[[files]]
path = "/etc/tedge/plugins/tedge-log-plugin.toml"
type = "tedge-log-plugin"
user = "tedge"
group = "tedge"
mode = 0o0644
