#:schema https://gist.githubusercontent.com/reubenmiller/4e28e8403fe0c54b7461ac7d1d6838c2/raw/b8599ccf81120bb22bdaa164655e2cc0b8fcb902/tedge.workflow.json
operation = "firmware_update"
on_error = "failed"

[init]
action = "proceed"
on_success = "scheduled"

[scheduled]
action = "proceed"
on_success = "executing"

[executing]
script = "/usr/bin/rugpi_workflow.sh ${.payload.status}"
on_success = "download"
on_error = { status = "failed", reason = "Refusing to start update as the wrong partition is active" }

[download]
script = "/usr/bin/rugpi_workflow.sh ${.payload.status} --url ${.payload.remoteUrl}"
on_success = "install"
on_error = { status = "failed", reason = "Failed to download image"}

[install]
script = "/usr/bin/rugpi_workflow.sh ${.payload.status} --url ${.payload.url}"
on_success = "restart"
on_error = { status = "failed", reason = "Failed to install image"}

[restart]
action = "restart"
on_exec = "restarting"  # Internal state used by the "restart" action
on_success = "restarted"
on_error = { status = "failed_restart", reason = "Failed to restart device" }

[restarted]
script = "/usr/bin/rugpi_workflow.sh ${.payload.status}"
on_success = "verify"
on_error = { status = "rollback_restart", reason = "Unexpected error during restarted check. Rolling back"}

[failed_restart]
script = "/usr/bin/rugpi_workflow.sh failed_restart"
on_success = { status = "failed", reason = "Device failed to restart" }

[verify]
script = "/usr/bin/rugpi_workflow.sh ${.payload.status} --firmware-name ${.payload.name} --firmware-version ${.payload.version} --url ${.payload.remoteUrl}"
on_exit.0 = { status = "commit" }
on_exit.4 = { status = "rollback_restart", reason = "Verification failed. Rolling back to default partition" }
on_exit._ = { status = "failed", reason = "Verification failed, no rollback necessary" }

[commit]
script = "/usr/bin/rugpi_workflow.sh ${.payload.status} --firmware-name ${.payload.name} --firmware-version ${.payload.version} --url ${.payload.remoteUrl}"
on_success = "successful"
on_error = { status = "rollback_restart", reason = "Commit failed. Rolling back to default partition" }

[rollback_restart]
action = "restart"
on_exec = "restarting"  # Internal state used by the "restart" action
on_success = "rollback_successful"

[rollback_successful]
script = "/usr/bin/rugpi_workflow.sh ${.payload.status}"
on_success = { status = "failed", reason = "Firmware update failed, but the rollback to the default partition was successful" }

[successful]
action = "cleanup"

[failed]
action = "cleanup"
